# Generated by Django 6.0.1 on 2026-04-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_stockreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã Voucher')),
                ('discount_amount', models.IntegerField(verbose_name='Số tiền giảm (VND)')),
                ('active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
            ],
        ),
    ]
