# Generated by Django 6.0.1 on 2026-04-28 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_flashsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0, verbose_name='Giảm bao nhiêu % ?'),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.flashsale', verbose_name='Tham gia Sự kiện Sale'),
        ),
    ]
