# Generated by Django 6.0.1 on 2026-04-30 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_stock_restored'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockreceipt',
            options={'verbose_name': 'Phiếu nhập kho', 'verbose_name_plural': '9. Quản lý Kho'},
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Số lượng nhập'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_amount',
            field=models.IntegerField(default=0, verbose_name='Số tiền giảm (VND)'),
        ),
    ]
