# Generated by Django 6.0.1 on 2026-05-01 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_stockreceipt_options_and_more'),
        ('app', '0019_alter_voucher_discount_amount'),
    ]

    operations = [
    ]
