# Generated by Django 6.0.1 on 2026-03-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do trả hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đã xác nhận', 'Đã xác nhận'), ('Đang giao', 'Đang giao'), ('Đã giao', 'Đã giao'), ('Yêu cầu trả hàng', 'Yêu cầu trả hàng'), ('Đã trả hàng/Hoàn tiền', 'Đã trả hàng/Hoàn tiền'), ('Đã hủy', 'Đã hủy')], default='Chờ xác nhận', max_length=50, verbose_name='Trạng thái đơn hàng'),
        ),
    ]
