# Generated by Django 6.0.1 on 2026-03-13 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_return_reason_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Tên Size (S, M, L, XL...)')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': '7. Quản lý Size',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Size đã chọn'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung đánh giá')),
                ('rating', models.IntegerField(default=5, verbose_name='Số sao (1-5)')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': '8. Quản lý Đánh giá',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='app.size', verbose_name='Các size hiện có'),
        ),
    ]
