# Generated by Django 6.0.1 on 2026-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên sự kiện (VD: Đại lễ 30/4)')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Phần trăm giảm (%)')),
                ('start_date', models.DateTimeField(verbose_name='Bắt đầu từ')),
                ('end_date', models.DateTimeField(verbose_name='Kết thúc lúc')),
                ('active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
            ],
        ),
    ]
