# Generated by Django 6.0.1 on 2026-04-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_stock_restored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount_amount',
            field=models.IntegerField(default=0, verbose_name='Số tiền giảm (VND)'),
        ),
    ]
