"""
Django settings for webbanhang project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv:
    load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0f07m*t)_8@#g@=8zhp0x!xevbf&9bysg()hh-wij^tc%flc&e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://*.lhr.life', 'https://*.trycloudflare.com']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webbanhang.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Sửa dòng này để Django tìm vào đúng thư mục app/templates
        'DIRS': [BASE_DIR / 'app' / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webbanhang.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# webbanhang/settings.py

# 1. Đường dẫn URL để truy cập tệp tĩnh
STATIC_URL = 'static/'

# 2. Khai báo thư mục chứa tệp tĩnh
# Chỉ dùng thư mục đang tồn tại để tránh cảnh báo staticfiles.W004
STATICFILES_DIRS = [
    BASE_DIR / 'app' / 'static',
]

MEDIA_URL = '/images/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'app/static/images')
JAZZMIN_SETTINGS = {
    # Tên hiển thị trên tab trình duyệt
    "site_title": "Quản trị Shoppyy",
    
    # Tên hiển thị ở góc trái trên cùng của menu
    "site_header": "Shoppyy Admin",
    
    # Tên thương hiệu hiển thị trên trang đăng nhập
    "site_brand": "Shoppyy Fashion",
    
    # Lời chào trên trang đăng nhập
    "welcome_sign": "Chào mừng đến với hệ thống quản trị Shoppyy",

    # === ĐÂY LÀ PHẦN TẠO NÚT TRỎ RA TRANG CHỦ BÁN HÀNG ===
    "topmenu_links": [
        # Link 1: Trở về bảng điều khiển (Dashboard)
        {"name": "Trang chủ Admin",  "url": "admin:index"},
        
        # Link 2: Trỏ thẳng ra ngoài trang web bán hàng của bạn
        # "new_window": True giúp mở web ở một tab mới để không mất trang admin đang xem
        {"name": "🛒 Mở trang bán hàng", "url": "/", "new_window": True},
    ],
    # ====================================================

    # Tùy biến icon cho các bảng (Tùy chọn cho đẹp mắt)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "app.category": "fas fa-list",     # Nhớ thay 'app' bằng tên thư mục app của bạn nhé
        "app.product": "fas fa-box",
        "app.order": "fas fa-shopping-cart",
        "app.orderitem": "fas fa-boxes",
        "app.shippingaddress": "fas fa-map-marked-alt",
    },
    
    # Giấu dòng chữ "UI Builder" ở góc phải
    "show_ui_builder": False,
}
# In email ra màn hình Terminal để test Quên mật khẩu
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# CẤU HÌNH GỬI EMAIL THẬT QUA GMAIL
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Không ghi Gmail và App Password trực tiếp trong code.
# Hãy tạo file .env cùng cấp manage.py và khai báo:
# EMAIL_HOST_USER=your_email@gmail.com
# EMAIL_HOST_PASSWORD=your_app_password
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# --- CẤU HÌNH NGÔN NGỮ VÀ MÚI GIỜ ---
LANGUAGE_CODE = 'vi'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_TZ = False

# --- CẤU HÌNH ĐỊNH DẠNG TIỀN TỆ (DẤU CHẤM) ---
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','
NUMBER_GROUPING = 3